title: saasan.github.io
url: "http://saasan.github.io"
twitter:
  username: saasan
github_username:  saasan

highlighter: false

sass:
  style: compressed
  sass_dir: css

paginate: 5
paginate_path: "/blog/page:num/"

gems:
  - jekyll-paginate
  - jekyll-redirect-from
