title: slx.jp
author: saasan
copyright: "(c) {currentYear} {author}"
url: "https://slx.jp"
favicon: "/assets/images/favicon.png"
twitter_username: saasan
github_username: saasan
default_image: "/assets/images/favicon.png"
include:
  - .nojekyll
  - .well-known/
exclude:
  - _posts/*-README.md
  - _posts/*-CHANGELOG.md

yat:
  date_format: "%Y-%m-%d %H:%M"
sitemap: true
lang: "ja"
translate_langs: []
night_mode: "manual"
code_badge:
  enabled: "false"
header_pages:
  - index.html
  - archives.html
  - categories.html
  - tags.html

paginate: 5
paginate_path: "/blog/page:num/"

theme: jekyll-theme-yat

# highlighter: rouge
# markdown: kramdown
# kramdown:
#   input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
