title: saasan.github.io
url: "http://saasan.github.io"
author_name: saasan
twitter_username: saasan
github_username:  saasan
default_image: "/img/s2works_favicon.png"

paginate: 5
paginate_path: "/blog/page:num/"

sass:
  sass_dir: css

gems:
  - jekyll-paginate
  - jekyll-gist
  - octopress-autoprefixer
  - htmlbeautifier
  - jekyll-sitemap
