title: saasan.github.io
url: "https://saasan.github.io"
author_name: saasan
twitter_username: saasan
github_username: saasan
default_image: "/img/s2works_favicon.png"
include:
  - .nojekyll
  - .well-known/
exclude:
  - software/*/*.md

paginate: 5
paginate_path: "/blog/page:num/"

sass:
  sass_dir: css

plugins:
  - jekyll-paginate
  - jekyll-gist
  - htmlbeautifier
  - jekyll-sitemap
