title: saasan.github.io
url: "http://saasan.github.io"
twitter:
  username: saasan
github_username:  saasan

highlighter: false

paginate: 5
paginate_path: "/blog/page:num/"

gems:
  - jekyll-assets
  - jekyll-paginate
