title: saasan.github.io
url: "http://saasan.github.io"
author_name: saasan
twitter_username: saasan
github_username:  saasan
default_image: "/img/s2works_favicon.png"

highlighter: false

paginate: 5
paginate_path: "/blog/page:num/"

gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-gist
